- hosts: metricbeat-servers
  vars:
    metricbeat_url: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.11.2-x86_64.rpm"
  become: yes
  tasks:
    - name: Download metricbeat rpm package
      get_url:
        url: "{{ metricbeat_url }}"
        dest: "/tmp/{{ metricbeat_url | basename }}"
      register: metricbeat_download

    - name: Install metricbeat rpm package
      yum:
        name: "/tmp/{{ metricbeat_url | basename }}"
        state: present

    - name: Replace metricbeat config file
      copy:
        src: ./includes/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Replace metricbeat system module config file
      copy:
        src: ./includes/system.yml
        dest: /etc/metricbeat/modules.d/system.yml

    - name: Enable metricbeat system module
      command: metricbeat modules enable system

    - name: Setup metricbeat
      command: metricbeat setup

    - name: Start metricbeat service
      service:
        name: metricbeat
        state: restarted
        enabled: yes
