# The same name used in inventory file will be the hostname of the server.
- hosts: all
  become: true
  tasks: 
    - name: setup hostname for servers
      command: hostnamectl set-hostname "{{ inventory_hostname }}"
      # command: hostnamectl set-hostname "{{ inventory_hostname }}.myapp.com"
    - name: get-hostname
      command: hostname
      register: hostname_result
    - name: display-hostname
      debug:
        msg: "The hostname is: {{ hostname_result.stdout }}"